::WALLET REPOSITORY
::IF POOL SUPPORTS MINING DIRECTLY TO AN EXCHANGE, FOLLOW THEIR INSTRUCTIONS ON HOW TO ADD THE PAYMENT ID TO THE END OF THE WALLET ADDRESS

SET BTC=
SET BTCP=
SET DGB=
SET ELLA=
SET AKA=
SET ETC=
SET ETH=
SET ETN=
SET EXP=
SET FTC=
SET KMD=
SET KRB=
SET MONA=
SET MUS=
SET PGN=
SET PIRL=
SET RVN=
SET SUMO=
SET UBQ=
SET VTC=
SET XMR=
SET XZC=
SET ZCL=
SET ZEC=
SET ZEN=

::MINER & LOGIN INFORMATION
:: *** Miner login for pools like suprnova.cc
:: *** dont get excited, our primary mining weblogin is not bitsbetrippin, used as example
:: *** MUST UPDATE JSON FILE FOR NVIDIA XMR FOR USER INFO

SET MINER_WEBLOGIN=bitsbetrippin
SET WORKER_PASSWORD=x
SET MINER_NAME=bbtworker01
SET EMAIL_ADDRESS=bitsbetrippin1@gmail.com
