@echo off
setx GPU_FORCE_64BIT_PTR 0
ECHO GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 99
ECHO GPU_MAX_HEAP_SIZE 99
setx GPU_MAX_USE_SYNC_OBJECTS 1
ECHO GPU_MAX_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 99
ECHO GPU_MAX_ALLOC_PERCENT 99
setx GPU_MAX_SINGLE_ALLOC_PERCENT 99
ECHO GPU_MAX_SINGLE_ALLOC_PERCENT 99
xmrig-amd.exe
pause